mysite/urls.py
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gaestd_py_django_local_static]
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("polls.urls")),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# [END gaestd_py_django_local_static]

polls/urls.py
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('content/', views.content, name='content'),
    path('request/', views.request, name='request'),
    path('register/', views.register, name='register'),
    path('view_request_list/<int:puid>/', views.view_request_list, name='view_request_list'),
    path('view_content_list/<path:url_inp>/', views.view_content_list, name='view_content_list'),
    path('view_user_list/', views.view_user_list, name='view_user_list'),
    path('login/<str:email_inp>/<str:password_inp>/', views.login, name='login'),
    path('<path:url>/', views.get_content_list, name='get_content_list')
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polls/models.py
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.db import models
from django.utils import timezone
import datetime

class Account(models.Model):
    userid = models.AutoField(primary_key = True, unique=True)
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    email = models.CharField(unique=True, max_length=50)
    start_date = models.DateField(auto_now_add=True)
    end_date = models.DateField(blank=True, null=True)

    class Meta:
        abstract = True

class Priviligeduser(Account):
    user_role = models.CharField(max_length=50, blank=True, null=True)
    class Meta:
        db_table = 'priviligeduser'

#class Admin(Account):
    #priviligeduserid = models.OneToOneField(Priviligeduser, models.DO_NOTHING, db_column='priviligeduserid', blank=True, null=True)
    #class Meta:
        #db_table = 'admin'

#class Moderator(Account):
    #priviligeduserid = models.OneToOneField(Priviligeduser, models.DO_NOTHING, db_column='priviligeduserid', blank=True, null=True)
    #class Meta:
        #db_table = 'moderator'
class Baseuser(Account):
    maxcontent = models.IntegerField(blank=True, null=True)
    dailycontentmarked = models.IntegerField(blank=True, null=True)
    maxmetdate = models.DateTimeField(blank=True, null=True)
    maxmet = models.BooleanField(blank=True, null=True)
    def reset_limit(self):
        return self.maxmetdate <= timezone.now() - datetime.timedelta(days=1) and self.maxmet==True

    class Meta:
        db_table = 'baseuser'



class Request(models.Model):
    r_id = models.AutoField(primary_key=True, unique = True)
    baseuserid = models.ForeignKey(Baseuser, models.DO_NOTHING, db_column='baseuserid', blank=True, null=True)
    time_stamp = models.DateTimeField(auto_now=True)
    user_role = models.CharField(max_length=30)
    url = models.CharField(max_length=500)
    identifier = models.CharField(max_length=300)
    reason = models.CharField(max_length=300)
    placeholder = models.CharField(max_length=300)
    isresolved = models.BooleanField(blank=True, null=True)

    class Meta:
        abstract = True

class Createrequest(Request):
    priviligeduserid = models.ForeignKey('Priviligeduser', models.DO_NOTHING,  db_column='priviligeduserid', blank=True, null=True)

    class Meta:
        db_table = 'createrequest'


class Content(models.Model):
    c_id = models.AutoField(primary_key=True, unique = True)
    priviligeduserid = models.OneToOneField('Priviligeduser', models.DO_NOTHING,  db_column='priviligeduserid', blank=True, null=True)
    create_r_id = models.OneToOneField('Createrequest', models.DO_NOTHING, db_column='create_r_id', blank=True, null=True)
    time_stamp = models.DateTimeField(auto_now=True)
    user_role = models.CharField(max_length=30)
    url = models.CharField(max_length=500)
    identifier = models.CharField(max_length=300)
    reason = models.CharField(max_length=300)
    placeholder = models.CharField(max_length=300)
    isblocked = models.BooleanField(blank=True, null=True)

    class Meta:
        db_table = 'content'

class Reportrequest(Request):
    c = models.OneToOneField(Content, models.DO_NOTHING, db_column='c_id', db_index=False, blank=True, null=True)
    priviligeduserid = models.ForeignKey(Priviligeduser, models.DO_NOTHING, db_index=False, db_column='priviligeduserid', blank=True, null=True)

    class Meta:
        db_table = 'reportrequest'

polls/templates/polls/content.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <form action="{% url 'polls:view_content_list' url_inp %}" method="post">
        <fieldset>
            {% if content_exists %}
            <legend><h1>Content</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <div class="table">
            {% for content in content_exists %}
                <div class="row">
                    <div class="cell"><p>Content:{{content.identifier}}&emsp;Reason:{{content.reason}}&emsp;Placeholder:{{content.placeholder}}&emsp;isblocked:{{content.isblocked}}</p></div>
                </div>
            {% endfor %}
            </div>
            {% else %}
            <p>No content is blocked for this url.</p>
            {% endif %}
        </fieldset>
        <input type="submit" value="Done">
    </form>

polls/templates/polls/detail.html
{% comment %}
Copyright 2021 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
{% endcomment %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% comment %}
Copyright 2021 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
{% endcomment %}

Hello, world. You're at the polls index.

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/request.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <form action="{% url 'polls:view_request_list' puid %}" method="post">
        <fieldset>
            {% if create_request_exists %}
            <legend><h1>Create Requests</h1></legend>
            {% if error_message1 %}<p><strong>{{ error_message1 }}</strong></p>{% endif %}
            <div class="table">
            {% for request in create_request_exists %}
                <div class="row">
                    <div class="cell"><label for="request{{ forloop.counter }}">Approve</label><br></div>
                    <div class="cell"><input type="checkbox" name="approve_create_request{{ request.r_id }}" id="request{{ forloop.counter }}" value="True"></div>
                    <div class="cell"><label for="request{{ forloop.counter }}">Disapprove</label><br></div>
                    <div class="cell"><input type="checkbox" name="dissaprove_create_request{{ request.r_id }}" id="request{{ forloop.counter }}" value="True"></div>
                    <div class="cell"><p>ContenttoReplace:{{request.identifier}}&emsp;User:{{request.baseuserid.userid}}&emsp;Reason:{{request.reason}}&emsp;Placeholder:{{request.placeholder}}&emsp;URL:{{request.url}}</p></div>
                </div>
            {% endfor %}
            </div>
            {% else %}
            <p>No create_requests are available.</p>
            {% endif %}
        </fieldset>
        <fieldset>
            {% if report_request_exists %}
            <legend><h1>Report Requests</h1></legend>
            {% if error_message2 %}<p><strong>{{ error_message2 }}</strong></p>{% endif %}
            <div class="table">
            {% for request in report_request_exists %}
                <div class="row">
                    <div class="cell"><label for="request{{ forloop.counter }}">Approve</label><br></div>
                    <div class="cell"><input type="checkbox" name="approve_report_request{{ request.r_id }}" id="request{{ forloop.counter }}" value="True"></div>
                    <div class="cell"><label for="request{{ forloop.counter }}">Disapprove</label><br></div>
                    <div class="cell"><input type="checkbox" name="disapprove_report_request{{ request.r_id }}" id="request{{ forloop.counter }}" value="True"></div>
                    <div class="cell"><p>ContentbeingReplaced:{{request.identifier}}&emsp;User:{{request.baseuserid.userid}}&emsp;Reason:{{request.reason}}&emsp;Placeholder:{{request.placeholder}}&emsp;URL:{{request.url}}</p></div>
                </div>
            {% endfor %}
            </div>
            {% else %}
            <p>No report_requests are available.</p>
            {% endif %}
        </fieldset>
        <input type="reset" value="Refresh">
        <input type="submit" value="Done">
        </form>

polls/templates/polls/results.html
{% comment %}
Copyright 2021 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
{% endcomment %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/users.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <form action="{% url 'polls:view_user_list' %}" method="post">
        <fieldset>
            {% if user_exists %}
            <legend><h1>Baseusers</h1></legend>
            {% if error_message1 %}<p><strong>{{ error_message1 }}</strong></p>{% endif %}
            <div class="table">
            {% for user in user_exists %}
                <div class="row">
                    <div class="cell"><label for="baseuser{{ forloop.counter }}">Update to Mod</label><br></div>
                    <div class="cell"><input type="checkbox" name="baseuser_to_mod{{ user.userid }}" id="baseuser{{ forloop.counter }}" value="True"></div>
                    <div class="cell"><label for="baseuser{{ forloop.counter }}">Update to Admin</label><br></div>
                    <div class="cell"><input type="checkbox" name="baseuser_to_admin{{ user.userid }}" id="baseuser{{ forloop.counter }}" value="True"></div>
                    <div class="cell"><p> User:{{user.userid}}&emsp;Name:{{user.name}}&emsp;email:{{user.email}}</p></div>
                    <div class="cell"><label for="baseuser{{ forloop.counter }}">Delete</label><br></div>
                    <div class="cell"><input type="checkbox" name="delete_baseuser{{ user.userid }}" id="baseuser{{ forloop.counter }}" value="True"></div>
                </div>
            {% endfor %}
            </div>
            {% else %}
            <p>No baseusers exist.</p>
            {% endif %}
        </fieldset>
        <fieldset>
            {% if mod_exists %}
            <legend><h1>Moderators</h1></legend>
            {% if error_message2 %}<p><strong>{{ error_message2 }}</strong></p>{% endif %}
            <div class="table">
            {% for user in mod_exists %}
                <div class="row">
                    <div class="cell"><label for="mod{{ forloop.counter }}">Demote to Baseuser</label><br></div>
                    <div class="cell"><input type="checkbox" name="mod_to_baseuser{{ user.userid }}" id="mod{{ forloop.counter }}" value="True"></div>
                    <div class="cell"><label for="mod{{ forloop.counter }}">Update to Admin</label><br></div>
                    <div class="cell"><input type="checkbox" name="mod_to_admin{{ user.userid }}" id="mod{{ forloop.counter }}" value="True"></div>
                    <div class="cell"><p> User:{{user.userid}}&emsp;Name:{{user.name}}&emsp;email:{{user.email}}</p></div>
                    <div class="cell"><label for="mod{{ forloop.counter }}">Delete</label><br></div>
                    <div class="cell"><input type="checkbox" name="delete_mod{{ user.userid }}" id="mod{{ forloop.counter }}" value="True"></div>
                </div>
            {% endfor %}
            </div>
            {% else %}
            <p>No moderators exist.</p>
            {% endif %}
        </fieldset>
        <fieldset>
            {% if admin_exists %}
            <legend><h1>Admins</h1></legend>
            {% if error_message3 %}<p><strong>{{ error_message3 }}</strong></p>{% endif %}
            <div class="table">
            {% for user in admin_exists %}
                <div class="row">
                    <div class="cell"><label for="admin{{ forloop.counter }}">Demote to Baseuser</label><br></div>
                    <div class="cell"><input type="checkbox" name="admin_to_baseuser{{ user.userid }}" id="admin{{ forloop.counter }}" value="True"></div>
                    <div class="cell"><label for="admin{{ forloop.counter }}">Demote to Mod</label><br></div>
                    <div class="cell"><input type="checkbox" name="admin_to_mod{{ user.userid }}" id="admin{{ forloop.counter }}" value="True"></div>
                    <div class="cell"><p> User:{{user.userid}}&emsp;Name:{{user.name}}&emsp;email:{{user.email}}</p></div>
                    <div class="cell"><label for="admin{{ forloop.counter }}">Delete</label><br></div>
                    <div class="cell"><input type="checkbox" name="delete_admin{{ user.userid }}" id="admin{{ forloop.counter }}" value="True"></div>
                </div>
            {% endfor %}
            </div>
            {% else %}
            <p>No admins exist.</p>
            {% endif %}
        </fieldset>
        <input type="reset" value="Refresh">
        <input type="submit" value="Done">
        </form>